const express = require('express');
const app = express();
const port = 8000;
app.use(express.json());

// előre definiált categories tömb
    const categories = [
    { "categoryID": 1, "category": "Család és szülők" },
    { "categoryID": 2, "category": "Életmód, egészség" },
    { "categoryID": 3, "category": "Életrajzok, visszaemlékezések" },
    { "categoryID": 4, "category": "Ezotéria" },
    { "categoryID": 5, "category": "Gasztronómia" },
    { "categoryID": 6, "category": "Gyermek és ifjúsági" },
    { "categoryID": 7, "category": "Hangoskönyv" },
    { "categoryID": 8, "category": "Hobbi, szabadidő" },
    { "categoryID": 9, "category": "Irodalom" },
    { "categoryID": 10, "category": "Képregény" },
    { "categoryID": 11, "category": "Kert, ház, otthon" },
    { "categoryID": 12, "category": "Lexikon, enciklopédia" },
    { "categoryID": 13, "category": "Művészet, építészet" },
    { "categoryID": 14, "category": "Napjaink, bulvár, politika" },
    { "categoryID": 15, "category": "Nyelvkönyv, szótár, idegen nyelvű" },
    { "categoryID": 16, "category": "Pénz, gazdaság, üzleti élet" },
    { "categoryID": 17, "category": "Sport, természetjárás" },
    { "categoryID": 18, "category": "Számítástechnika, internet" },
    { "categoryID": 19, "category": "Tankönyvek, segédkönyvek" },
    { "categoryID": 20, "category": "Társ. tudományok" }
    ];

    const users = [
        {
          "userID": "1",
          "admin": false,
          "email": "kis.ildikó@gmail.com",
          "name": "Kis Ildikó",
          "phone": "+36448619537",
          "zip": "9022",
          "city": "Kecskemét",
          "address": "Bethlen Gábor utca 10",
          "password": "461c65df3de0dfbe1c08e96474132e56a2276964dc9795ba1f0a6e07fe02b7c1"
        },
        {
          "userID": "2",
          "admin": false,
          "email": "farkas.anna@gmail.com",
          "name": "Farkas Anna",
          "phone": "+36705333534",
          "zip": "6000",
          "city": "Budapest",
          "address": "Vörösmarty Mihály utca 59",
          "password": "05a08f959b357114608b49622adcffcfee67d6552baa6f3ed0d52b3baf892425"
        },
        {
          "userID": "3",
          "admin": false,
          "email": "kovács.gábor@gmail.com",
          "name": "Kovács Gábor",
          "phone": "+36313761359",
          "zip": "3300",
          "city": "Pécs",
          "address": "Petőfi Sándor utca 67",
          "password": "460b5d16ef3e1c9adcb4df05528de09f6dd1a52c23fa389cd1a3b622bf17ca7f"
        },
        {
          "userID": "4",
          "admin": true,
          "email": "kis.mihály@gmail.com",
          "name": "Kis Mihály",
          "phone": "+36283812511",
          "zip": "1117",
          "city": "Győr",
          "address": "Széchenyi István utca 12",
          "password": "b36fd0d07cf023eba3f48ff7c7d4ec21e6190ba786b65a5444188084622f4173"
        },
        {
          "userID": "5",
          "admin": false,
          "email": "kiss.erzsébet@gmail.com",
          "name": "Kiss Erzsébet",
          "phone": "+36467935377",
          "zip": "1011",
          "city": "Miskolc",
          "address": "Petőfi Sándor utca 4",
          "password": "bf32ae577bd6c4908fa7124b701a50264323a2efab844ace48ee84f73ce527f0"
        },
        {
          "userID": "6",
          "admin": false,
          "email": "nagy.ildikó@gmail.com",
          "name": "Nagy Ildikó",
          "phone": "+36579609477",
          "zip": "1011",
          "city": "Szeged",
          "address": "Hunyadi János utca 97",
          "password": "75d793207006cd760f0d6834267e94129f7f5503c60ad11ccaf6ed8b6bdb2882"
        },
        {
          "userID": "7",
          "admin": false,
          "email": "farkas.lászló@gmail.com",
          "name": "Farkas László",
          "phone": "+36627956808",
          "zip": "9022",
          "city": "Debrecen",
          "address": "Széchenyi István utca 46",
          "password": "11fcba5e98e33ff8ce390ef3a8799efbacb1cc3bdb92b04534415a7c7b720e03"
        },
        {
          "userID": "8",
          "admin": false,
          "email": "szabó.gábor@gmail.com",
          "name": "Szabó Gábor",
          "phone": "+36447801348",
          "zip": "1117",
          "city": "Pécs",
          "address": "Vörösmarty Mihály utca 25",
          "password": "feebc3441f1c1b37d7286e1ac157b036344df90dd50d430f49f4b7c5f7651b63"
        },
        {
          "userID": "9",
          "admin": false,
          "email": "kiss.mihály@gmail.com",
          "name": "Kiss Mihály",
          "phone": "+36229831952",
          "zip": "9400",
          "city": "Budapest",
          "address": "Jókai Mór utca 61",
          "password": "40a057627c36b3b0f0acbdcfba6e820a697bbecdd9edbb795bedb1e7dd0a6204"
        },
        {
          "userID": "10",
          "admin": false,
          "email": "farkas.brigi@gmail.com",
          "name": "Farkas Brigi",
          "phone": "+36457731097",
          "zip": "1011",
          "city": "Miskolc",
          "address": "Bethlen Gábor utca 40",
          "password": "8618a2ecd5ddb347cd27a943a051516130836b1d9a6ad56c163980fcc5966a70"
        },
        {
          "userID": "11",
          "admin": false,
          "email": "kis.mihály@gmail.com",
          "name": "Kis Mihály",
          "phone": "+36403299034",
          "zip": "6000",
          "city": "Nyíregyháza",
          "address": "Bethlen Gábor utca 33",
          "password": "44241bc33b7385e4685b45983cbbee00f2871ea8ed367a5364661d266115c4c4"
        },
        {
          "userID": "12",
          "admin": false,
          "email": "farkas.józsef@gmail.com",
          "name": "Farkas József",
          "phone": "+36691996646",
          "zip": "7621",
          "city": "Szeged",
          "address": "Bethlen Gábor utca 60",
          "password": "2f197b2acf4fcc06a02c2e18f1940a031f160627b6ff987d944289cbd41354ab"
        },
        {
          "userID": "13",
          "admin": false,
          "email": "kiss.gábor@gmail.com",
          "name": "Kiss Gábor",
          "phone": "+36682912493",
          "zip": "9400",
          "city": "Szeged",
          "address": "Hunyadi János utca 17",
          "password": "044ca2008ae1da8757f7a1f9375e1950a4dd538b3c07589b692d355dd96cf5ca"
        },
        {
          "userID": "14",
          "admin": false,
          "email": "farkas.brigi@gmail.com",
          "name": "Farkas Brigi",
          "phone": "+36577898316",
          "zip": "9400",
          "city": "Székesfehérvár",
          "address": "Széchenyi István utca 61",
          "password": "2d4971271f3ace451cbe9441914f10e8d12e62d2f7c1d4995378ec64071703cd"
        },
        {
          "userID": "15",
          "admin": false,
          "email": "farkas.mihály@gmail.com",
          "name": "Farkas Mihály",
          "phone": "+36671789221",
          "zip": "1117",
          "city": "Nyíregyháza",
          "address": "Petőfi Sándor utca 38",
          "password": "9d3d2da0b0872e02a29922ed7a5b0418b59c57fa21e2cf104dd183cf78b08608"
        },
        {
          "userID": "16",
          "admin": false,
          "email": "tóth.zsuzsa@gmail.com",
          "name": "Tóth Zsuzsa",
          "phone": "+36287834117",
          "zip": "7621",
          "city": "Kecskemét",
          "address": "Hunyadi János utca 5",
          "password": "5fdc7951c34bbdab8b2c7a0baf6aa94b10d094a9abb178b2982915a72bf4da1f"
        },
        {
          "userID": "17",
          "admin": false,
          "email": "nagy.zsuzsa@gmail.com",
          "name": "Nagy Zsuzsa",
          "phone": "+36298382908",
          "zip": "6000",
          "city": "Nyíregyháza",
          "address": "Attila utca 2",
          "password": "fb28ceeb74dc97244228516df89c12c450d21bf8159befe4e8e2969faf7a53b2"
        },
        {
          "userID": "18",
          "admin": false,
          "email": "molnár.gábor@gmail.com",
          "name": "Molnár Gábor",
          "phone": "+36219163311",
          "zip": "4031",
          "city": "Székesfehérvár",
          "address": "Attila utca 26",
          "password": "9d2aead16471fecfa03488176861f9c937d790b7da9b793f8659c1e09ba39d9d"
        },
        {
          "userID": "19",
          "admin": false,
          "email": "varga.gábor@gmail.com",
          "name": "Varga Gábor",
          "phone": "+36509222726",
          "zip": "6720",
          "city": "Győr",
          "address": "Attila utca 82",
          "password": "e377372440a1ce45e4535d45060477201ad507020ae1d8d9773a2fd3cdbdc464"
        },
        {
          "userID": "20",
          "admin": false,
          "email": "tóth.lászló@gmail.com",
          "name": "Tóth László",
          "phone": "+36465150720",
          "zip": "3300",
          "city": "Miskolc",
          "address": "Vörösmarty Mihály utca 54",
          "password": "51fa5eb780fd864f5e8caf136f49ec892f216a60f5be8b3e020de25178eebb10"
        },
        {
          "userID": "21",
          "admin": false,
          "email": "kis.ildikó@gmail.com",
          "name": "Kis Ildikó",
          "phone": "+36347380945",
          "zip": "8000",
          "city": "Pécs",
          "address": "Petőfi Sándor utca 79",
          "password": "1164cd70a2256119ba9c3a81aa3fd50a7fa883b54e82ef9711c3a98631d35cf7"
        },
        {
          "userID": "22",
          "admin": false,
          "email": "nagy.katalin@gmail.com",
          "name": "Nagy Katalin",
          "phone": "+36234085222",
          "zip": "7621",
          "city": "Budapest",
          "address": "Hunyadi János utca 30",
          "password": "330006b80ce08a50e77edb4c5b25cdb9a7106d2f5816f4d7076e9cc42838ea8b"
        },
        {
          "userID": "23",
          "admin": false,
          "email": "kiss.gábor@gmail.com",
          "name": "Kiss Gábor",
          "phone": "+36603327768",
          "zip": "8000",
          "city": "Debrecen",
          "address": "Kossuth Lajos utca 86",
          "password": "c170f29f33ebb5cb06e51f7cc75748652e5623b09c1fc67727712d63faf66039"
        },
        {
          "userID": "24",
          "admin": false,
          "email": "molnár.józsef@gmail.com",
          "name": "Molnár József",
          "phone": "+36265318957",
          "zip": "1011",
          "city": "Miskolc",
          "address": "Hunyadi János utca 22",
          "password": "c49840a831595e96f6f07863b48bf25c487e5c1e0f9752bcd7f080dd18254c0a"
        },
        {
          "userID": "25",
          "admin": false,
          "email": "varga.zsuzsa@gmail.com",
          "name": "Varga Zsuzsa",
          "phone": "+36526233438",
          "zip": "4031",
          "city": "Debrecen",
          "address": "Széchenyi István utca 99",
          "password": "ae04917fe079c43c9c39cfbadea8c8b2fe9b48f97a34e51a5bd058e6f8d1289d"
        },
        {
          "userID": "26",
          "admin": false,
          "email": "molnár.anna@gmail.com",
          "name": "Molnár Anna",
          "phone": "+36287544621",
          "zip": "9400",
          "city": "Miskolc",
          "address": "Vörösmarty Mihály utca 40",
          "password": "6d8c2ead1d06019f6ca252977a24d2bdd8982988a2a5a07c1cf45c588613377a"
        },
        {
          "userID": "27",
          "admin": false,
          "email": "horváth.mihály@gmail.com",
          "name": "Horváth Mihály",
          "phone": "+36346658020",
          "zip": "4031",
          "city": "Miskolc",
          "address": "Széchenyi István utca 100",
          "password": "bd557f1c89dfcabb728658ed6f09cb125c6795363f0dc0b87e22581e5f93872d"
        },
        {
          "userID": "28",
          "admin": false,
          "email": "kis.mihály@gmail.com",
          "name": "Kis Mihály",
          "phone": "+36469141801",
          "zip": "9022",
          "city": "Szeged",
          "address": "Bethlen Gábor utca 75",
          "password": "434fb13a056aa255c9676ae8c72ad7f8b0ac5ffb2c90e0eca05bd06fb86f4229"
        },
        {
          "userID": "29",
          "admin": false,
          "email": "kiss.zsuzsa@gmail.com",
          "name": "Kiss Zsuzsa",
          "phone": "+36285146175",
          "zip": "8000",
          "city": "Győr",
          "address": "Bethlen Gábor utca 50",
          "password": "18b4a167b26697bcfc558fee39fab8d9b4c005653ede29eec5295d3e5b76681a"
        },
        {
          "userID": "30",
          "admin": false,
          "email": "molnár.erzsébet@gmail.com",
          "name": "Molnár Erzsébet",
          "phone": "+36339329252",
          "zip": "1117",
          "city": "Nyíregyháza",
          "address": "Széchenyi István utca 11",
          "password": "c23e66b50fcbf33bec62730faa75afe93b3ad5e12f961db746cb6ce681faebb0"
        },
        {
          "userID": "31",
          "admin": false,
          "email": "varga.katalin@gmail.com",
          "name": "Varga Katalin",
          "phone": "+36282400014",
          "zip": "9022",
          "city": "Kecskemét",
          "address": "Attila utca 79",
          "password": "e8538592e29b8ef7232a2f8787a2a9e6023e60908f8b553dc8767364e5494d56"
        },
        {
          "userID": "32",
          "admin": false,
          "email": "varga.anna@gmail.com",
          "name": "Varga Anna",
          "phone": "+36204998836",
          "zip": "9022",
          "city": "Miskolc",
          "address": "Kossuth Lajos utca 95",
          "password": "1a239dab31df65e3bcbc79500f9481987424f41ceb2930d12b95a7361a47a756"
        },
        {
          "userID": "33",
          "admin": false,
          "email": "szabó.erzsébet@gmail.com",
          "name": "Szabó Erzsébet",
          "phone": "+36226468262",
          "zip": "7621",
          "city": "Miskolc",
          "address": "Hunyadi János utca 67",
          "password": "7d2e2197dd1210e399c318f4bf975f188cb6b71c6bdd9d84176ae5a28dd59484"
        },
        {
          "userID": "34",
          "admin": false,
          "email": "szabó.gábor@gmail.com",
          "name": "Szabó Gábor",
          "phone": "+36462700503",
          "zip": "4031",
          "city": "Nyíregyháza",
          "address": "Széchenyi István utca 55",
          "password": "801abb17671159c000fdcfee1f4246fc06954550fa8ea557f6b96453b3253103"
        },
        {
          "userID": "35",
          "admin": false,
          "email": "kovács.zsuzsa@gmail.com",
          "name": "Kovács Zsuzsa",
          "phone": "+36682641501",
          "zip": "9022",
          "city": "Budapest",
          "address": "Ady Endre utca 55",
          "password": "76297823b09895620fe99df21eb90da0ec8fcbd1ebc9eb7f21f475ffa8d3839a"
        },
        {
          "userID": "36",
          "admin": false,
          "email": "kovács.mihály@gmail.com",
          "name": "Kovács Mihály",
          "phone": "+36569635289",
          "zip": "9400",
          "city": "Győr",
          "address": "Vörösmarty Mihály utca 29",
          "password": "d7c52c5451005af008ddf09ae0abbe0646911467c4f91af755a23752e80236d3"
        },
        {
          "userID": "37",
          "admin": false,
          "email": "kovács.mihály@gmail.com",
          "name": "Kovács Mihály",
          "phone": "+36707599530",
          "zip": "7621",
          "city": "Sopron",
          "address": "Ady Endre utca 89",
          "password": "9a846243a1af0d7d9113b3b48b0ac6b422434204aea290c57fa1d98497a81f64"
        },
        {
          "userID": "38",
          "admin": false,
          "email": "molnár.józsef@gmail.com",
          "name": "Molnár József",
          "phone": "+36598231181",
          "zip": "4031",
          "city": "Szeged",
          "address": "Vörösmarty Mihály utca 95",
          "password": "9fd564b0ed3ea01d8589faebadd53232638e3a6e4053ec676afeb5f9fe015be6"
        },
        {
          "userID": "39",
          "admin": false,
          "email": "farkas.anna@gmail.com",
          "name": "Farkas Anna",
          "phone": "+36644118217",
          "zip": "7621",
          "city": "Debrecen",
          "address": "Hunyadi János utca 52",
          "password": "64926c932713af989cf60083519176134a01009b275c17eec7aa6b6ccb34e24e"
        },
        {
          "userID": "40",
          "admin": false,
          "email": "molnár.lászló@gmail.com",
          "name": "Molnár László",
          "phone": "+36661609491",
          "zip": "4031",
          "city": "Szeged",
          "address": "Bethlen Gábor utca 67",
          "password": "d9d5c42ed8cb7991d478a4489c3dd622a2b0878bc9579701043becc6ad6c8453"
        },
        {
          "userID": "41",
          "admin": false,
          "email": "farkas.gábor@gmail.com",
          "name": "Farkas Gábor",
          "phone": "+36372779143",
          "zip": "6720",
          "city": "Győr",
          "address": "Bethlen Gábor utca 41",
          "password": "ed3a2ad7b2f044b04f6b88abaeafe9c94abc28817c03d0febfb52e4c3bdf0c94"
        },
        {
          "userID": "42",
          "admin": false,
          "email": "nagy.brigi@gmail.com",
          "name": "Nagy Brigi",
          "phone": "+36424193657",
          "zip": "1011",
          "city": "Székesfehérvár",
          "address": "Kossuth Lajos utca 59",
          "password": "ffd2533a43527beb26bb0e12baa821c925d0bdc99b64889a50409540036c2597"
        },
        {
          "userID": "43",
          "admin": false,
          "email": "szabó.gábor@gmail.com",
          "name": "Szabó Gábor",
          "phone": "+36626478881",
          "zip": "6000",
          "city": "Kecskemét",
          "address": "Vörösmarty Mihály utca 57",
          "password": "75d793207006cd760f0d6834267e94129f7f5503c60ad11ccaf6ed8b6bdb2882"
        },
        {
          "userID": "44",
          "admin": false,
          "email": "kovács.brigi@gmail.com",
          "name": "Kovács Brigi",
          "phone": "+36224113270",
          "zip": "1011",
          "city": "Győr",
          "address": "Vörösmarty Mihály utca 82",
          "password": "0f95aa58f51d00d5d2769f85aac77af592503631e40297c25a289acd034c3dc9"
        },
        {
          "userID": "45",
          "admin": false,
          "email": "tóth.józsef@gmail.com",
          "name": "Tóth József",
          "phone": "+36395268363",
          "zip": "9400",
          "city": "Nyíregyháza",
          "address": "Vörösmarty Mihály utca 89",
          "password": "28397203011d2b851a34e1af6d919dd8ecedd65f30ef9442d229be0c9c0b24bf"
        },
        {
          "userID": "46",
          "admin": false,
          "email": "molnár.mihály@gmail.com",
          "name": "Molnár Mihály",
          "phone": "+36317373681",
          "zip": "6000",
          "city": "Miskolc",
          "address": "Arany János utca 73",
          "password": "10b8079236206155af9a693b3ba27926392bb97ec819f20be7b3510903e8b781"
        },
        {
          "userID": "47",
          "admin": false,
          "email": "nagy.anna@gmail.com",
          "name": "Nagy Anna",
          "phone": "+36247551685",
          "zip": "3300",
          "city": "Pécs",
          "address": "Attila utca 95",
          "password": "3d6f2b8e9f67e183d66f15f52763f7de44b2103384160c012fecd6127265404b"
        },
        {
          "userID": "48",
          "admin": false,
          "email": "farkas.gábor@gmail.com",
          "name": "Farkas Gábor",
          "phone": "+36566831393",
          "zip": "1011",
          "city": "Sopron",
          "address": "Jókai Mór utca 66",
          "password": "36386ac7de9699b2bdf8e4ff3f9c92b576766bffb7896303d9bd67a7216f6ae1"
        },
        {
          "userID": "49",
          "admin": false,
          "email": "molnár.brigi@gmail.com",
          "name": "Molnár Brigi",
          "phone": "+36333555361",
          "zip": "6720",
          "city": "Székesfehérvár",
          "address": "Arany János utca 57",
          "password": "930a5d6391d6a0bf5d649701cdf5647c855f4957c14e3298d32aa25286ec9ff1"
        },
        {
          "userID": "50",
          "admin": false,
          "email": "szabó.zsuzsa@gmail.com",
          "name": "Szabó Zsuzsa",
          "phone": "+36688030615",
          "zip": "9400",
          "city": "Székesfehérvár",
          "address": "Attila utca 14",
          "password": "4c60dd3415bde0fad67d1ec1ad8cfdb76b8a5fa4dd311554b02247ca3f3d80e1"
        }
      ]
      

    const books = [
        
            {
                "bookID": "1",
                "author": "Kertész Ákos",
                "title": "Szülők és gyerekek",
                "publisher": "Corvina Kiadó",
                "the_year_of_publishing": "2010",
                "description": "A Szülők és gyerekek egy útmutató a hatékony szülői neveléshez, amely a modern pszichológia és pedagógia legújabb eredményeit ötvözi. Általános és specifikus tanácsokat kínál a különböző életkorú gyermekek neveléséhez, és segít megérteni a gyermek fejlődési folyamatait.",
                "language": "magyar",
                "number_of_pages": "224",
                "cover": "puha",
                "weight": "220gr",
                "ISBN": "9789631355107",
                "itemcode": "1098321 / 934821",
                "price": "3500",
                "discounted_price": "2800",
                "book_url": "https://arthobby.hu/shop_ordered/27703/pic/LIBRI_2.png",
                "categoryID": 1
            },
            {
                "author": "Tóth Krisztina",
                "title": "Az egészséges életmód titkai",
                "publisher": "Europa Könyvkiadó",
                "the_year_of_publishing": "2018",
                "description": "Az egészséges életmód titkai egy átfogó útmutató a testi és lelki egészség megőrzéséhez. A könyvben szereplő tanácsok segítenek egészségesebben étkezni, rendszeresen mozogni, stresszkezelési technikákat alkalmazni és kiegyensúlyozott életet élni.",
                "language": "magyar",
                "number_of_pages": "288",
                "cover": "puha",
                "weight": "280gr",
                "ISBN": "9789631355121",
                "itemcode": "798532 / 692418",
                "price": "3800",
                "discounted_price": "3000",
                "book_url": "https://libris.to/media/jacket/33635519o.jpg",
                "categoryID": 2
            },
            {
                "author": "Michelle Obama",
                "title": "Becoming: Az életem",
                "publisher": "Crown Publishing Group",
                "the_year_of_publishing": "2018",
                "description": "Az Az életem egy inspiráló életrajzi mű Michelle Obama tollából, az Egyesült Államok egykori első hölgyének személyes történetét meséli el, beleértve gyermekkorát Chicagóban, karrierjét, anyaságát és az elnöki hivatalban töltött éveket.",
                "language": "angol",
                "number_of_pages": "426",
                "cover": "keménytáblás",
                "weight": "580gr",
                "ISBN": "9781524763138",
                "itemcode": "632189 / 539218",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "https://arthobby.hu/shop_ordered/27703/pic/LIBRI_2.png",
                "categoryID": 3
            },
            {
                "author": "Deepak Chopra",
                "title": "Az isteni szinkronicitás",
                "publisher": "Cassandra Kiadó",
                "the_year_of_publishing": "2012",
                "description": "Az Isti szinkronicitás egy spirituális könyv, amely arra ösztönzi az olvasót, hogy figyeljen az élet apró jeleire és szinkronjaira, melyek vezethetnek bennünket az önmegvalósítás és boldogság felé vezető úton.",
                "language": "magyar",
                "number_of_pages": "192",
                "cover": "puha",
                "weight": "240gr",
                "ISBN": "9789639553994",
                "itemcode": "451298 / 392471",
                "price": "3200",
                "discounted_price": "2500",
                "book_url": "",
                "categoryID": 4
            },
            {
                "author": "Jamie Oliver",
                "title": "Jamie Oliver 5",
                "publisher": "Penguin Books",
                "the_year_of_publishing": "2014",
                "description": "Az Jamie Oliver 5 egy egyszerű és ízletes recepteket tartalmazó szakácskönyv, amely az egészséges és gyorsan elkészíthető ételek iránt érdeklődőknek szól. Minden recept csak öt fő összetevőt tartalmaz, és könnyen elkészíthető.",
                "language": "angol",
                "number_of_pages": "320",
                "cover": "keménytáblás",
                "weight": "700gr",
                "ISBN": "9780718157807",
                "itemcode": "892371 / 743982",
                "price": "3900",
                "discounted_price": "3100",
                "book_url": "",
                "categoryID": 5
            },
            {
                "author": "Roald Dahl",
                "title": "Matilda",
                "publisher": "Puffin Books",
                "the_year_of_publishing": "1988",
                "description": "Matilda egy fantasztikus gyermekkönyv Roald Dahl tollából, amely egy kisfiúról szól, aki különleges képességekkel rendelkezik. Matilda tele van humorral, kalanddal és tanulságokkal a jó és rossz között.",
                "language": "angol",
                "number_of_pages": "240",
                "cover": "puha",
                "weight": "250gr",
                "ISBN": "9780142410370",
                "itemcode": "682319 / 591432",
                "price": "2900",
                "discounted_price": "2300",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a Főnix Rendje",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2003",
                "description": "Harry Potter és barátai összefognak az iskolájukat fenyegető sötét erőkkel szemben. Ez a könyv az ő kalandjaikról szól, ahogy megküzdnek a gonosszal és a barátságuk még erősebbé válik.",
                "language": "angol",
                "number_of_pages": "768",
                "cover": "keménytáblás",
                "weight": "900gr",
                "ISBN": "9781408855690",
                "itemcode": "928174 / 812341",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 7
            },
            {
                "author": "Molnár Ferenc",
                "title": "Vadkacsa",
                "publisher": "Magvető Kiadó",
                "the_year_of_publishing": "1918",
                "description": "A Vadkacsa egy klasszikus magyar novella, amely egy kisfiú és egy vadkacsa barátságáról szól, akik együtt játszanak és kalandokat élnek át a Tisza partján. Molnár Ferenc műve örökérvényű tanulságokat tartalmaz az emberség fontosságáról.",
                "language": "magyar",
                "number_of_pages": "128",
                "cover": "puha",
                "weight": "150gr",
                "ISBN": "9789631424504",
                "itemcode": "524137 / 421983",
                "price": "2500",
                "discounted_price": "2000",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "Stan Lee",
                "title": "Spider-Man: Homecoming",
                "publisher": "Marvel Comics",
                "the_year_of_publishing": "2017",
                "description": "A Spider-Man: Homecoming egy izgalmas képregény, amely a hős kalandjait követi nyomon, miközben megpróbálja egyensúlyban tartani a hétköznapi életét és a szuperhőssé válást.",
                "language": "angol",
                "number_of_pages": "144",
                "cover": "keménytáblás",
                "weight": "300gr",
                "ISBN": "9781302902758",
                "itemcode": "432196 / 359721",
                "price": "2800",
                "discounted_price": "2200",
                "book_url": "",
                "categoryID": 10
            },
            {
                "author": "Monty Don",
                "title": "A kertész naplója",
                "publisher": "Dorling Kindersley",
                "the_year_of_publishing": "2003",
                "description": "A Kertész naplója Monty Don népszerű televíziós kertész munkáját mutatja be. A könyvben található tanácsok és ötletek segítséget nyújtanak a kertészkedéshez, a növények gondozásához és a kert tervezéséhez.",
                "language": "angol",
                "number_of_pages": "352",
                "cover": "keménytáblás",
                "weight": "700gr",
                "ISBN": "9781405318859",
                "itemcode": "593218 / 482317",
                "price": "3200",
                "discounted_price": "2500",
                "book_url": "",
                "categoryID": 11
            },
            {
                "author": "John Gray",
                "title": "Az okos város",
                "publisher": "Libri Kiadó",
                "the_year_of_publishing": "2017",
                "description": "Az Okos város egy lexikon a városfejlesztés, az urbanizáció és az okos város fogalmairól. A könyv bemutatja az innovatív városi megoldásokat és technológiákat, amelyek segítik a városok fenntartható fejlődését és a lakók életminőségének javítását.",
                "language": "magyar",
                "number_of_pages": "416",
                "cover": "puha",
                "weight": "480gr",
                "ISBN": "9789633106271",
                "itemcode": "721834 / 609321",
                "price": "3900",
                "discounted_price": "3100",
                "book_url": "",
                "categoryID": 12
            },
            {
                "author": "Vincent van Gogh",
                "title": "Vincent van Gogh: Művészete",
                "publisher": "Taschen",
                "the_year_of_publishing": "2015",
                "description": "A Vincent van Gogh: Művészete egy gyönyörűen illusztrált könyv, amely bemutatja a híres holland festő legfontosabb műveit és életét. A kötet gazdag szövegekkel és reprodukciókkal segít megérteni van Gogh művészi vízióit és alkotói folyamatát.",
                "language": "angol",
                "number_of_pages": "272",
                "cover": "keménytáblás",
                "weight": "1100gr",
                "ISBN": "9783836505634",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 13
            },
            {
                "author": "Péterfy Gergely",
                "title": "A férfi",
                "publisher": "Magvető Kiadó",
                "the_year_of_publishing": "2018",
                "description": "A Férfi egy tabudöntögető regény a modern férfiasságról, amely bemutatja a férfiak különböző életútjait és küzdelmeit. Péterfy Gergely érzékeny és provokatív írásmódja megragadja az olvasót és elgondolkodtatja őket a férfi identitásról.",
                "language": "magyar",
                "number_of_pages": "384",
                "cover": "puha",
                "weight": "420gr",
                "ISBN": "9789631445172",
                "itemcode": "498217 / 421483",
                "price": "3800",
                "discounted_price": "3000",
                "book_url": "",
                "categoryID": 14
            },
            {
                "author": "Lonely Planet",
                "title": "Angol-magyar szótár",
                "publisher": "Lonely Planet",
                "the_year_of_publishing": "2019",
                "description": "Az Angol-magyar szótár egy alapvető languagekönyv mindazoknak, akik angolul tanulnak vagy kommunikálni szeretnének angolul. A szótárban található szavak és kifejezések segítenek az angol language gyorsabb és hatékonyabb elsajátításában.",
                "language": "angol",
                "number_of_pages": "672",
                "cover": "puha",
                "weight": "520gr",
                "ISBN": "9789633187989",
                "itemcode": "389421 / 318974",
                "price": "3500",
                "discounted_price": "2800",
                "book_url": "",
                "categoryID": 15
            },
            {
                "author": "Warren Buffett",
                "title": "A Warren Buffett mód",
                "publisher": "Portfolio",
                "the_year_of_publishing": "2006",
                "description": "A Warren Buffett mód egy inspiráló könyv a befektetési stratégiák és a pénzügyi siker titkairól. Warren Buffett, az egyik leggazdagabb ember a világon, megosztja tapasztalatait és tanácsait arról, hogyan lehet sikeresen befektetni és gazdagodni.",
                "language": "angol",
                "number_of_pages": "320",
                "cover": "keménytáblás",
                "weight": "450gr",
                "ISBN": "9781591840911",
                "itemcode": "749231 / 641872",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 16
            },
            {
                "author": "Daniel Kahneman",
                "title": "Gondolkodj gyorsan, gondolkodj lassan",
                "publisher": "HVG Kiadó",
                "the_year_of_publishing": "2012",
                "description": "A Gondolkodj gyorsan, gondolkodj lassan egy pszichológiai könyv, amely bemutatja az emberi gondolkodás különböző folyamatait és hibáit. Daniel Kahneman Nobel-díjas pszichológus átfogóan elemzi a döntéshozatali mechanizmusokat és azok hatásait az életünkre.",
                "language": "magyar",
                "number_of_pages": "560",
                "cover": "puha",
                "weight": "650gr",
                "ISBN": "9789633042133",
                "itemcode": "682314 / 589213",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 20
            },
            {
                "author": "J. K. Rowling",
                "title": "Quidditch a világ körül",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2001",
                "description": "A Quidditch a világ körül egy fantasztikus sportkönyv, amely bemutatja a híres Harry Potter világ legnépszerűbb sportjának részleteit és történetét. A könyv számos érdekességet tartalmaz a quidditch játékról, a csapatokról és a versenyekről.",
                "language": "angol",
                "number_of_pages": "56",
                "cover": "puha",
                "weight": "120gr",
                "ISBN": "9780747556423",
                "itemcode": "279431 / 241782",
                "price": "2500",
                "discounted_price": "2000",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Bear Grylls",
                "title": "A túlélés útja",
                "publisher": "HarperCollins",
                "the_year_of_publishing": "2014",
                "description": "A Túlélés útja egy praktikus útmutató a túlélési technikákhoz és túlélési helyzetek kezeléséhez. Bear Grylls, a túlélőműsorok ismert szereplője megosztja tapasztalatait és tanácsait arról, hogyan lehet túlélni vészhelyzetekben a vadonban.",
                "language": "angol",
                "number_of_pages": "416",
                "cover": "keménytáblás",
                "weight": "700gr",
                "ISBN": "9780007287757",
                "itemcode": "532187 / 451982",
                "price": "3900",
                "discounted_price": "3100",
                "book_url": "",
                "categoryID": 17
            },
            {
                "author": "Bill Gates",
                "title": "A jövő eleje",
                "publisher": "Corvina Kiadó",
                "the_year_of_publishing": "2015",
                "description": "A Jövő eleje egy könyv a technológia és a jövőbeli trendek jövőbeli hatásairól. Bill Gates, a Microsoft alapítója és filantrópja megosztja gondolatait az innováció, a robotika és a mesterséges intelligencia fejlődéséről.",
                "language": "magyar",
                "number_of_pages": "304",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9789631355473",
                "itemcode": "673215 / 582134",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 18
            },
            {
                "author": "John Green",
                "title": "Turtles All the Way Down",
                "publisher": "Dutton Books",
                "the_year_of_publishing": "2017",
                "description": "A Turtles All the Way Down egy ifjúsági regény, amely egy tinédzser lány küzdelmeiről szól a mentális betegségekkel és a barátsággal. John Green érzékenyen és őszintén írja le a főszereplő belső vívódásait és a gyógyulás felé vezető utat.",
                "language": "angol",
                "number_of_pages": "304",
                "cover": "keménytáblás",
                "weight": "450gr",
                "ISBN": "9780525555360",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "Tim Ferriss",
                "title": "A 4 órás munkahét",
                "publisher": "HVG Kiadó",
                "the_year_of_publishing": "2011",
                "description": "A 4 órás munkahét egy könyv a hatékony időgazdálkodás és a munkaélet egyensúlyának megteremtéséről. Tim Ferriss bemutatja azokat az újító technikákat és gondolkodásmódokat, amelyek lehetővé teszik, hogy kevesebb időt dolgozzunk és többet élvezzünk az életből.",
                "language": "magyar",
                "number_of_pages": "352",
                "cover": "puha",
                "weight": "480gr",
                "ISBN": "9789633042355",
                "itemcode": "682314 / 589213",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 8
            },
            {
                "author": "Jókai Mór",
                "title": "Az arany ember",
                "publisher": "Magvető Kiadó",
                "the_year_of_publishing": "1873",
                "description": "Az Arany ember Jókai Mór klasszikus regénye, amely a török uralom alatti Magyarország életét és harcát mutatja be. A történet egy gazdag aranybányászról szól, aki a szerelem és az árulás viharos tengerén keresztül keresi boldogságát.",
                "language": "magyar",
                "number_of_pages": "560",
                "cover": "keménytáblás",
                "weight": "800gr",
                "ISBN": "9789631445172",
                "itemcode": "498217 / 421483",
                "price": "3800",
                "discounted_price": "3000",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "Neil Gaiman",
                "title": "Sandman Vol. 1: Prelúdiumok é éjféli történetek",
                "publisher": "Vertigo",
                "the_year_of_publishing": "1989",
                "description": "A Sandman egy kultikus képregénysorozat Neil Gaiman tollából, amely a különleges és misztikus álmok birodalmába vezeti az olvasót. A Prelúdiumok és éjféli történetek kötet az első része a sorozatnak, amely bemutatja a főszereplő, Morpheus karakterét és világát.",
                "language": "angol",
                "number_of_pages": "240",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9781401225759",
                "itemcode": "832153 / 701294",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 10
            },
            {
                "author": "Martha Stewart",
                "title": "Martha Stewart's Homekeeping Handbook",
                "publisher": "Clarkson Potter Publishers",
                "the_year_of_publishing": "2006",
                "description": "A Martha Stewart's Homekeeping Handbook egy átfogó útmutató a háztartási feladatokhoz és otthoni gondozáshoz. Martha Stewart részletesen bemutatja a takarítási, főzési és dekorációs technikákat, amelyek segítenek fenntartani egy tiszta és rendezett otthont.",
                "language": "angol",
                "number_of_pages": "752",
                "cover": "keménytáblás",
                "weight": "1800gr",
                "ISBN": "9780517577004",
                "itemcode": "921384 / 791423",
                "price": "4800",
                "discounted_price": "3800",
                "book_url": "",
                "categoryID": 11
            },
            {
                "author": "Péterfy Gergely",
                "title": "A borító",
                "publisher": "Magvető Kiadó",
                "the_year_of_publishing": "2014",
                "description": "A Borító egy regény az irodalom és az identitás kereséséről, amely egy fiatal íróról és könyvszerkesztőről szól, aki váratlanul találkozik az irodalmi múlttal és az elveszett szerelmeivel. Péterfy Gergely stílusa és languagei játékossága lenyűgözi az olvasót és magával ragadja őket a történetbe.",
                "language": "magyar",
                "number_of_pages": "432",
                "cover": "puha",
                "weight": "500gr",
                "ISBN": "9789631445172",
                "itemcode": "498217 / 421483",
                "price": "3800",
                "discounted_price": "3000",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "David Copperfield",
                "title": "My Secrets of Magic",
                "publisher": "Penguin Books",
                "the_year_of_publishing": "2002",
                "description": "A My Secrets of Magic egy varázslatos könyv David Copperfield tollából, amely bemutatja a világhírű varázsló legjobb trükkjeit és technikáit. A könyvben található útmutatások segítenek az olvasónak megtanulni néhány egyszerű varázslatos mutatványt.",
                "language": "angol",
                "number_of_pages": "176",
                "cover": "puha",
                "weight": "300gr",
                "ISBN": "9780142300445",
                "itemcode": "921384 / 791423",
                "price": "4800",
                "discounted_price": "3800",
                "book_url": "",
                "categoryID": 8
            },
            {
                "author": "Závada Pál",
                "title": "A regény mestersége",
                "publisher": "Magvető Kiadó",
                "the_year_of_publishing": "2018",
                "description": "A Regény mestersége egy írói kézikönyv, amely bemutatja az alkotói folyamat lépéseit és titkait. Závada Pál részletesen elemzi az írói technikákat és eszközöket, amelyek segítenek létrehozni egy sikeres regényt.",
                "language": "magyar",
                "number_of_pages": "320",
                "cover": "puha",
                "weight": "400gr",
                "ISBN": "9789631445172",
                "itemcode": "498217 / 421483",
                "price": "3800",
                "discounted_price": "3000",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "Rick Riordan",
                "title": "Percy Jackson és az olimposziak",
                "publisher": "Hyperion Books",
                "the_year_of_publishing": "2005",
                "description": "A Percy Jackson és az olimposziak egy izgalmas ifjúsági fantasy-sorozat Rick Riordan tollából, amely az ókori görög mitológiára épül. A főszereplő, Percy Jackson, egy hétköznapi fiú, aki rádöbben, hogy istenek és szörnyek világában kell megküzdenie a túlélésért.",
                "language": "angol",
                "number_of_pages": "384",
                "cover": "puha",
                "weight": "450gr",
                "ISBN": "9780786838653",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "Liane Moriarty",
                "title": "Az asszony a kabinban",
                "publisher": "HarperCollins",
                "the_year_of_publishing": "2018",
                "description": "Az Asszony a kabinban egy pszichológiai thriller, amely egy luxusjacht rejtélyes eltűnéséről szól. Liane Moriarty ügyesen fonja össze a múltat és a jelent, miközben a főszereplőknek meg kell küzdeniük a múltjukkal és a titkaikkal.",
                "language": "angol",
                "number_of_pages": "400",
                "cover": "puha",
                "weight": "550gr",
                "ISBN": "9781250301697",
                "itemcode": "421341 / 359823",
                "price": "3900",
                "discounted_price": "3100",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "J.D. Salinger",
                "title": "A 20. század hírmondója",
                "publisher": "Penguin Books",
                "the_year_of_publishing": "1951",
                "description": "A 20. század hírmondója egy klasszikus amerikai regény J.D. Salinger tollából, amely a fiatal Holden Caulfield történetét meséli el. A könyv a fiatalság, az elidegenedés és az identitás keresésének témáit járja körül éles megfigyelőképességgel és humorral.",
                "language": "angol",
                "number_of_pages": "288",
                "cover": "keménytáblás",
                "weight": "400gr",
                "ISBN": "9780241950425",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 3
            },
            {
                "author": "Sheryl Sandberg",
                "title": "Lean In: Women, Work, and the Will to Lead",
                "publisher": "Knopf",
                "the_year_of_publishing": "2013",
                "description": "A Lean In egy inspiráló könyv a nők vezetéséről és az egyenlőségről a munkahelyen. Sheryl Sandberg, a Facebook vezető operatív igazgatója megosztja tapasztalatait és tanácsait arról, hogyan lehet sikeresen navigálni a karrierjében és hatékonyan támogatni más nőket.",
                "language": "angol",
                "number_of_pages": "240",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9780385349949",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID":16
            },
            {
                "author": "Malcolm Gladwell",
                "title": "Outliers: The Story of Success",
                "publisher": "Little, Brown and Company",
                "the_year_of_publishing": "2008",
                "description": "Az Outliers egy könyv a siker titkairól és azokról a tényezőkről, amelyek meghatározzák az emberek kivételes teljesítményét. Malcolm Gladwell elemzi a sikeres emberek életét és körülményeit, és megvizsgálja, mi teszi őket kiemelkedővé a többiek közül.",
                "language": "angol",
                "number_of_pages": "320",
                "cover": "keménytáblás",
                "weight": "600gr",
                "ISBN": "9780316017930",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID":16
            },
            {
                "author": "Paulo Coelho",
                "title": "Az Alkimista",
                "publisher": "HarperCollins",
                "the_year_of_publishing": "1988",
                "description": "Az Alkimista egy spirituális regény Paulo Coelho tollából, amely egy fiatal pásztor kalandjait meséli el az álmok és a sors követése útján. A történet mély bölcsességeket tartalmaz az élet értelméről és az egyéni küldetés megtalálásáról.",
                "language": "magyar",
                "number_of_pages": "208",
                "cover": "puha",
                "weight": "250gr",
                "ISBN": "9789632633770",
                "itemcode": "532187 / 451982",
                "price": "3900",
                "discounted_price": "3100",
                "book_url": "",
                "categoryID": 3
            },
            {
                "author": "Marie Kondo",
                "title": "A renddel a lelkekhez",
                "publisher": "Tuttle Publishing",
                "the_year_of_publishing": "2019",
                "description": "A Renddel a lelkekhez egy könyv a minimalizmus és a rendszerezés művészetéről, amely segít megtalálni a boldogságot a hétköznapi életünkben. Marie Kondo bemutatja az összehajtogatás és az eldobás módszereit, amelyekkel rendezetté és harmóniássá tehetjük otthonunkat.",
                "language": "angol",
                "number_of_pages": "272",
                "cover": "keménytáblás",
                "weight": "800gr",
                "ISBN": "9780804189095",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Anthony Bourdain",
                "title": "Konyhakönyv",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2000",
                "description": "A Konyhakönyv egy világkörüli gasztronómiai kaland Anthony Bourdain szemszögéből, aki híres séf és gasztronómiai író. A könyvben található receptek és történetek segítenek felfedezni a különböző konyhák és ételek sokszínűségét a világ minden tájáról.",
                "language": "angol",
                "number_of_pages": "320",
                "cover": "keménytáblás",
                "weight": "900gr",
                "ISBN": "9780747544017",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 5
            },
            {
                "author": "Jamie Oliver",
                "title": "Jamie Oliver's Meals in Minutes",
                "publisher": "Michael Joseph",
                "the_year_of_publishing": "2011",
                "description": "A Jamie Oliver's Meals in Minutes egy könnyen követhető receptkönyv Jamie Oliver konyhaművészeti tippekkel és technikákkal. A könyvben található gyors és egyszerű receptek segítenek az embereknek egészséges és ízletes ételeket készíteni a mindennapokban.",
                "language": "angol",
                "number_of_pages": "288",
                "cover": "keménytáblás",
                "weight": "800gr",
                "ISBN": "9780718154776",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 5
            },
            {
                "author": "Donna Tartt",
                "title": "The Goldfinch",
                "publisher": "Little, Brown and Company",
                "the_year_of_publishing": "2013",
                "description": "A The Goldfinch egy regény Donna Tartt tollából, amely a művészet, a bűnözés és a szeretet témáit járja körül. A történet egy fiatal fiú életét követi, aki elveszíti édesanyját egy terrortámadásban, és egy különleges festményt próbál megmenteni az édesanyja emlékére.",
                "language": "angol",
                "number_of_pages": "784",
                "cover": "keménytáblás",
                "weight": "1100gr",
                "ISBN": "9780316055437",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 13
            },
            {
                "author": "Stephen King",
                "title": "The Shining",
                "publisher": "Doubleday",
                "the_year_of_publishing": "1977",
                "description": "A The Shining egy horror regény Stephen King tollából, amely egy elképesztően ijesztő hotelben játszódik. A történet egy elhagyatott szálloda gondnokáról szól, aki lassan elveszti az eszét a helyszín sötét titkaival való találkozás során.",
                "language": "angol",
                "number_of_pages": "688",
                "cover": "puha",
                "weight": "900gr",
                "ISBN": "9780307743657",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.R.R. Tolkien",
                "title": "The Hobbit",
                "publisher": "Houghton Mifflin Harcourt",
                "the_year_of_publishing": "1937",
                "description": "A The Hobbit egy fantasy regény J.R.R. Tolkien tollából, amely az elfek, törpök és sárkányok világába vezeti az olvasót. A történet egy szerény hobbit, Bilbo Baggins kalandjait meséli el, amikor egy váratlan kalandra indul egy aranyat hajszoló sárkány ellen.",
                "language": "angol",
                "number_of_pages": "304",
                "cover": "keménytáblás",
                "weight": "700gr",
                "ISBN": "9780547928227",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "Antoine de Saint-Exupéry",
                "title": "A kis herceg",
                "publisher": "Harper & Brothers",
                "the_year_of_publishing": "1943",
                "description": "A kis herceg egy gyermekkönyv Antoine de Saint-Exupéry tollából, amely a barátság, a szeretet és az emberi kapcsolatok témáit járja körül. A történet egy pilótáról szól, aki találkozik egy kisfiúval a sivatagban, aki az univerzum titkait és bölcsességeit osztja meg vele.",
                "language": "magyar",
                "number_of_pages": "96",
                "cover": "keménytáblás",
                "weight": "250gr",
                "ISBN": "9789630732523",
                "itemcode": "532187 / 451982",
                "price": "3900",
                "discounted_price": "3100",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "Elizabeth Gilbert",
                "title": "Eat, Pray, Love",
                "publisher": "Viking",
                "the_year_of_publishing": "2006",
                "description": "Az Eat, Pray, Love egy memoár Elizabeth Gilbert tollából, amely a szeretet, az önismeret és a boldogság keresését meséli el. Gilbert arról számol be, hogyan hagyta el a régi életét, hogy felfedezze a világ különböző kultúráit és önmagát az élet különböző területein.",
                "language": "angol",
                "number_of_pages": "368",
                "cover": "keménytáblás",
                "weight": "600gr",
                "ISBN": "9780670034710",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 3
            },
            {
                "author": "Eckhart Tolle",
                "title": "A Most hatalma",
                "publisher": "Penguin Books",
                "the_year_of_publishing": "1997",
                "description": "A Most hatalma egy spirituális könyv Eckhart Tolle tollából, amely az itt és most fontosságát hangsúlyozza az életben. Tolle arról ír, hogyan lehet megszabadulni az elménk által teremtett szenvedéstől és boldoggá válni a jelenben való elfogadással.",
                "language": "angol",
                "number_of_pages": "236",
                "cover": "puha",
                "weight": "300gr",
                "ISBN": "9781577314806",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 3
            },
            {
                "author": "Rhonda Byrne",
                "title": "The Secret",
                "publisher": "Atria Books",
                "the_year_of_publishing": "2006",
                "description": "A The Secret egy önismereti könyv Rhonda Byrne tollából, amely a pozitív gondolkodás erejét és az univerzum törvényeit mutatja be. Byrne azt állítja, hogy a vonzás törvénye segítségével az emberek bármilyen vágyukat elérhetik az életben.",
                "language": "angol",
                "number_of_pages": "198",
                "cover": "puha",
                "weight": "250gr",
                "ISBN": "9781582701707",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 3
            },
            {
                "author": "James Clear",
                "title": "Atomic Habits",
                "publisher": "Avery",
                "the_year_of_publishing": "2018",
                "description": "Az Atomic Habits egy önismereti könyv James Clear tollából, amely az apró változtatások fontosságát hangsúlyozza az életben. Clear megosztja tanácsait arról, hogyan lehet kialakítani és megerősíteni az egészséges szokásokat, hogy elérjük a céljainkat.",
                "language": "angol",
                "number_of_pages": "320",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9780735211292",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Jen Sincero",
                "title": "You Are a Badass",
                "publisher": "Running Press Adult",
                "the_year_of_publishing": "2013",
                "description": "A You Are a Badass egy önismereti könyv Jen Sincero tollából, amely az önelfogadás és a személyes fejlődés fontosságát hangsúlyozza. Sincero arról ír, hogyan lehet megtörni a korlátozó hiedelmeket és elérni az álmainkat a pozitív gondolkodás segítségével.",
                "language": "angol",
                "number_of_pages": "256",
                "cover": "puha",
                "weight": "300gr",
                "ISBN": "9780762447695",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Marie Forleo",
                "title": "Everything is Figureoutable",
                "publisher": "Portfolio",
                "the_year_of_publishing": "2019",
                "description": "A Everything is Figureoutable egy önismereti könyv Marie Forleo tollából, amely arra ösztönzi az embereket, hogy higgyenek a képességeikben és találjanak megoldást minden problémára az életben. Forleo inspiráló történetekkel és gyakorlati tanácsokkal segít az olvasóknak hozzáállni az élet kihívásaihoz.",
                "language": "angol",
                "number_of_pages": "304",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9780525534990",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Gabrielle Bernstein",
                "title": "The Universe Has Your Back",
                "publisher": "Hay House",
                "the_year_of_publishing": "2016",
                "description": "A The Universe Has Your Back egy önismereti könyv Gabrielle Bernstein tollából, amely az univerzum támogatásának és irányításának fontosságát hangsúlyozza az életben. Bernstein megosztja tapasztalatait és gyakorlati tanácsokat ad arról, hogyan lehet kapcsolatba lépni az univerzummal és elérni a céljainkat.",
                "language": "angol",
                "number_of_pages": "200",
                "cover": "puha",
                "weight": "250gr",
                "ISBN": "9781401946548",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Thich Nhat Hanh",
                "title": "The Miracle of Mindfulness",
                "publisher": "Beacon Press",
                "the_year_of_publishing": "1975",
                "description": "A The Miracle of Mindfulness egy önismereti könyv Thich Nhat Hanh tollából, amely a tudatosság és a jelenben való élés fontosságát hangsúlyozza az életben. Nhat Hanh megosztja a buddhista tanításokat és a meditáció gyakorlatait, amelyek segítenek az olvasónak megtalálni a békét és az örömöt a mindennapokban.",
                "language": "angol",
                "number_of_pages": "168",
                "cover": "puha",
                "weight": "200gr",
                "ISBN": "9780807012390",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Eckhart Tolle",
                "title": "A Most hatalma",
                "publisher": "Turtleback Books",
                "the_year_of_publishing": "1997",
                "description": "A Most hatalma egy spirituális könyv Eckhart Tolle tollából, amely az itt és most fontosságát hangsúlyozza az életben. Tolle arról ír, hogyan lehet megszabadulni az elménk által teremtett szenvedéstől és boldoggá válni a jelenben való elfogadással.",
                "language": "angol",
                "number_of_pages": "236",
                "cover": "keménytáblás",
                "weight": "300gr",
                "ISBN": "9780807012390",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "Dale Carnegie",
                "title": "How to Win Friends and Influence People",
                "publisher": "Simon & Schuster",
                "the_year_of_publishing": "1936",
                "description": "A How to Win Friends and Influence People egy önismereti könyv Dale Carnegie tollából, amely az emberi kapcsolatok és a sikeres kommunikáció fontosságát hangsúlyozza. Carnegie praktikus tanácsokat ad arról, hogyan lehet hatékonyan kommunikálni másokkal és befolyásolni őket.",
                "language": "angol",
                "number_of_pages": "288",
                "cover": "keménytáblás",
                "weight": "400gr",
                "ISBN": "9780671027032",
                "itemcode": "832142 / 721983",
                "price": "4200",
                "discounted_price": "3400",
                "book_url": "",
                "categoryID": 2
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a bölcsek köve",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "1997",
                "description": "A Harry Potter és a bölcsek köve egy fantasy regény J.K. Rowling tollából, amely a varázsvilágba kalauzolja az olvasót. A történet főszereplője, Harry Potter, egy fiatal varázsló, aki kalandok sorozatába keveredik a Roxfort Boszorkány- és Varázslóképző Szakiskolában.",
                "language": "magyar",
                "number_of_pages": "224",
                "cover": "keménytáblás",
                "weight": "400gr",
                "ISBN": "9789639563885",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a Titkok Kamrája",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "1998",
                "description": "A Harry Potter és a Titkok Kamrája folytatása a Harry Potter és a bölcsek köve titleű regénynek J.K. Rowling tollából, amely további kalandokat ígér a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry és barátai egy rejtélyes erővel szembesülnek a Roxfort falain belül.",
                "language": "magyar",
                "number_of_pages": "256",
                "cover": "keménytáblás",
                "weight": "450gr",
                "ISBN": "9789639563892",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és az Azkabani fogoly",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "1999",
                "description": "A Harry Potter és az Azkabani fogoly folytatása a Harry Potter és a Titkok Kamrája titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben egy titokzatos fogoly szökik meg Azkabanból, és fenyegetést jelent Harryre.",
                "language": "magyar",
                "number_of_pages": "320",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9789639563908",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a Tűz Serlege",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2000",
                "description": "A Harry Potter és a Tűz Serlege folytatása a Harry Potter és az Azkabani fogoly titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry részt vesz a Három Varázslók tornáján, ahol különböző varázslóiskolák diákjai mérkőznek meg egymással.",
                "language": "magyar",
                "number_of_pages": "640",
                "cover": "keménytáblás",
                "weight": "800gr",
                "ISBN": "9789639563915",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a Főnix Rendje",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2003",
                "description": "A Harry Potter és a Főnix Rendje folytatása a Harry Potter és a Tűz Serlege titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry és társai szembeszállnak egy sötét varázslóval és az őt támogató gonosz erőkkel.",
                "language": "magyar",
                "number_of_pages": "992",
                "cover": "keménytáblás",
                "weight": "1200gr",
                "ISBN": "9789639563939",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 6
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a Főnix Rendje",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2003",
                "description": "A Harry Potter és a Főnix Rendje folytatása a Harry Potter és a Tűz Serlege titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry és társai szembeszállnak egy sötét varázslóval és az őt támogató gonosz erőkkel.",
                "language": "angol",
                "number_of_pages": "992",
                "cover": "keménytáblás",
                "weight": "1200gr",
                "ISBN": "9789639563939",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Deathly Hallows",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2007",
                "description": "A Harry Potter and the Deathly Hallows folytatása a Harry Potter és a Főnix Rendje titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai az utolsó küldetésre indulnak, hogy legyőzzék a gonosz sötét varázslót, Voldemortot. A történetben Harrynek szembe kell néznie a múltjával és a jövőjével egyaránt, miközben az összes erőt és bátorságot összeszedi az utolsó csatára.",
                "language": "angol",
                "number_of_pages": "784",
                "cover": "keménytáblás",
                "weight": "1100gr",
                "ISBN": "9780545139700",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Philosopher's Stone",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "1997",
                "description": "A Harry Potter and the Philosopher's Stone egy fantasy regény J.K. Rowling tollából, amely a varázsvilágba kalauzolja az olvasót. A történet főszereplője, Harry Potter, egy fiatal varázsló, aki kalandok sorozatába keveredik a Roxfort Boszorkány- és Varázslóképző Szakiskolában.",
                "language": "angol",
                "number_of_pages": "223",
                "cover": "keménytáblás",
                "weight": "400gr",
                "ISBN": "9781408865262",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Chamber of Secrets",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "1998",
                "description": "A Harry Potter and the Chamber of Secrets folytatása a Harry Potter and the Philosopher's Stone titleű regénynek J.K. Rowling tollából, amely további kalandokat ígér a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry és barátai egy rejtélyes erővel szembesülnek a Roxfort falain belül.",
                "language": "angol",
                "number_of_pages": "251",
                "cover": "keménytáblás",
                "weight": "450gr",
                "ISBN": "9781408865262",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Prisoner of Azkaban",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "1999",
                "description": "A Harry Potter and the Prisoner of Azkaban folytatása a Harry Potter and the Chamber of Secrets titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben egy titokzatos fogoly szökik meg Azkabanból, és fenyegetést jelent Harryre.",
                "language": "angol",
                "number_of_pages": "317",
                "cover": "keménytáblás",
                "weight": "500gr",
                "ISBN": "9781408865262",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Goblet of Fire",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2000",
                "description": "A Harry Potter and the Goblet of Fire folytatása a Harry Potter and the Prisoner of Azkaban titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry részt vesz a Három Varázslók tornáján, ahol különböző varázslóiskolák diákjai mérkőznek meg egymással.",
                "language": "angol",
                "number_of_pages": "636",
                "cover": "keménytáblás",
                "weight": "800gr",
                "ISBN": "9781408865262",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Order of the Phoenix",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2003",
                "description": "A Harry Potter and the Order of the Phoenix folytatása a Harry Potter and the Goblet of Fire titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai egy újabb kalandra indulnak a Roxfort Boszorkány- és Varázslóképző Szakiskolában. A történetben Harry és társai szembeszállnak egy sötét varázslóval és az őt támogató gonosz erőkkel.",
                "language": "angol",
                "number_of_pages": "766",
                "cover": "keménytáblás",
                "weight": "1000gr",
                "ISBN": "9781408865262",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter and the Half-Blood Prince",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2005",
                "description": "A Harry Potter and the Half-Blood Prince folytatása a Harry Potter and the Order of the Phoenix titleű regénynek J.K. Rowling tollából, amelyben Harry és barátai az utolsó küldetésre indulnak, hogy legyőzzék a gonosz sötét varázslót, Voldemortot. A történetben Harrynek szembe kell néznie a múltjával és a jövőjével egyaránt, miközben az összes erőt és bátorságot összeszedi az utolsó csatára.",
                "language": "angol",
                "number_of_pages": "607",
                "cover": "keménytáblás",
                "weight": "900gr",
                "ISBN": "9781408865262",
                "itemcode": "832153 / 701294",
                "price": "4500",
                "discounted_price": "3600",
                "book_url": "",
                "categoryID": 9
            },
            {
                "author": "J.K. Rowling",
                "title": "Harry Potter és a Halál ereklyéi",
                "publisher": "Bloomsbury",
                "the_year_of_publishing": "2007",
                "description": "A Harry Potter és a Halál ereklyéi a Harry Potter sorozat utolsó kötete J.K. Rowling tollából, amelyben Harry és barátai az utolsó küldetésre indulnak, hogy legyőzzék a gonosz sötét varázslót, Voldemortot. A történetben Harrynek szembe kell néznie a múltjával és a jövőjével egyaránt, miközben az összes erőt és bátorságot összeszedi az utolsó csatára.",
                "language": "magyar",
                "number_of_pages": "608",
                "cover": "keménytáblás",
                "weight": "900gr",
                "ISBN": "9789639563953",
                "itemcode": "2779876 / 1222919",
                "price": "4250",
                "discounted_price": "3200",
                "book_url": "",
                "categoryID": 9
            }
        
      ];

// Middleware for setting up CORS headers
app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*'); // Minden eredet engedélyezve
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE'); // Engedélyezett HTTP műveletek
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization'); // Engedélyezett fejlécek
    next();
});

// Route to handle GET request for categories
app.get('/categories', (req, res) => {
    // Az előre definiált kategóriákat küldd vissza JSON formátumban
    res.json({categories});
});
app.get('/books', (req, res) => {
    // Az előre definiált kategóriákat küldd vissza JSON formátumban
    res.json({books});
});
app.get('/users', (req, res) => {
  // Az előre definiált kategóriákat küldd vissza JSON formátumban
  res.json({users});
});


app.listen(port, () => {
    console.log(`A szerver fut a http://localhost:${port} címen`);
});

app.post('/books', (req, res) => {
  const newBook = req.body;  // A kérés törzséből származó új könyvadatok
  books.push(newBook);       // Új könyv hozzáadása a 'books' tömbhöz
  res.status(201).json(newBook);  // Válasz küldése a hozzáadott könyvvel
});